board: [ "nice_nano_v2" ]
shield: [ "custom_16x6" ]
include:
  - board: nice_nano_v2
    shield: custom_16x6
    artifact-name: custom_16x6_keyboard
    cmake-args: -DEXTRA_BOARD_ROOT=/tmp/zmk-config/boards